image: node:8.16.2-alpine

stages:
  - install_Dependencies
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install_Dependencies
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

deploy_to_production:
  stage: deploy
  image: php:7.2-apache
  script:
    - curl -S "https://gitlab.com/chinloyal/ftp-deploy-tool/raw/master/deployment.phar" --output deployment.phar
    - echo remote = $FTP_HOST >> deployment.ini
    - echo user = $FTP_USER >> deployment.ini
    - echo password = $FTP_PASSWORD >> deployment.ini
    - php deployment.phar deployment.ini
  only:
  - master
